# Generated by Django 5.0.4 on 2025-05-05 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='ability',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='habit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='like',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
