# Generated by Django 5.0.4 on 2025-05-10 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_product_detail_ability_product_detail_habit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Product_detail_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='Product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.product'),
        ),
    ]
