# Generated by Django 5.0.4 on 2025-05-16 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_product_detail_ability_product_detail_habit_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='payment',
        #     name='product_detail_id',
        # ),
        # migrations.AddField(
        #     model_name='payment',
        #     name='Product_id',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.product'),
        # ),
        migrations.AlterField(
            model_name='review_shop',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.useri'),
        ),
    ]
